"""Initial GridGuard schema

Revision ID: faea4dc1dd55
Revises: None
Create Date: 2026-09-26 14:04:45.734996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'faea4dc1dd55'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('environmental_readings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('ambient_temperature', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('pressure', sa.Float(), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.Column('sea_surface_temp', sa.Float(), nullable=True),
    sa.Column('enso_status', sa.String(), nullable=True),
    sa.Column('enso_intensity', sa.String(), nullable=True),
    sa.Column('oni', sa.Float(), nullable=True),
    sa.Column('nino34', sa.Float(), nullable=True),
    sa.Column('condition', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_environmental_readings_timestamp'), 'environmental_readings', ['timestamp'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('report_type', sa.String(), nullable=False),
    sa.Column('date_range', sa.String(), nullable=False),
    sa.Column('file_format', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transformers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('transformer_code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('capacity', sa.String(), nullable=True),
    sa.Column('installation_date', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transformers_transformer_code'), 'transformers', ['transformer_code'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('alerts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('transformer_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('alert_type', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('acknowledged', sa.Boolean(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['transformer_id'], ['transformers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_timestamp'), 'alerts', ['timestamp'], unique=False)
    op.create_index(op.f('ix_alerts_transformer_id'), 'alerts', ['transformer_id'], unique=False)
    op.create_table('anomaly_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('transformer_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('anomaly_score', sa.Float(), nullable=False),
    sa.Column('reconstruction_error', sa.Float(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('is_anomaly', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('explanation', sa.String(), nullable=True),
    sa.Column('raw_features', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['transformer_id'], ['transformers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anomaly_results_timestamp'), 'anomaly_results', ['timestamp'], unique=False)
    op.create_index(op.f('ix_anomaly_results_transformer_id'), 'anomaly_results', ['transformer_id'], unique=False)
    op.create_table('health_scores',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('transformer_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('health_score', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('trend', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['transformer_id'], ['transformers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_scores_timestamp'), 'health_scores', ['timestamp'], unique=False)
    op.create_index(op.f('ix_health_scores_transformer_id'), 'health_scores', ['transformer_id'], unique=False)
    op.create_table('maintenance_recommendations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('transformer_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('risk_level', sa.String(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('recommended_actions', sa.JSON(), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('suggested_timeframe', sa.String(), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['transformer_id'], ['transformers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_recommendations_timestamp'), 'maintenance_recommendations', ['timestamp'], unique=False)
    op.create_index(op.f('ix_maintenance_recommendations_transformer_id'), 'maintenance_recommendations', ['transformer_id'], unique=False)
    op.create_table('sensor_readings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('transformer_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('ambient_temperature', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=False),
    sa.Column('vibration', sa.Float(), nullable=False),
    sa.Column('current', sa.Float(), nullable=False),
    sa.Column('voltage', sa.Float(), nullable=True),
    sa.Column('load', sa.Float(), nullable=True),
    sa.Column('power_factor', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['transformer_id'], ['transformers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_transformer_timestamp', 'sensor_readings', ['transformer_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_sensor_readings_timestamp'), 'sensor_readings', ['timestamp'], unique=False)
    op.create_index(op.f('ix_sensor_readings_transformer_id'), 'sensor_readings', ['transformer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sensor_readings_transformer_id'), table_name='sensor_readings')
    op.drop_index(op.f('ix_sensor_readings_timestamp'), table_name='sensor_readings')
    op.drop_index('idx_transformer_timestamp', table_name='sensor_readings')
    op.drop_table('sensor_readings')
    op.drop_index(op.f('ix_maintenance_recommendations_transformer_id'), table_name='maintenance_recommendations')
    op.drop_index(op.f('ix_maintenance_recommendations_timestamp'), table_name='maintenance_recommendations')
    op.drop_table('maintenance_recommendations')
    op.drop_index(op.f('ix_health_scores_transformer_id'), table_name='health_scores')
    op.drop_index(op.f('ix_health_scores_timestamp'), table_name='health_scores')
    op.drop_table('health_scores')
    op.drop_index(op.f('ix_anomaly_results_transformer_id'), table_name='anomaly_results')
    op.drop_index(op.f('ix_anomaly_results_timestamp'), table_name='anomaly_results')
    op.drop_table('anomaly_results')
    op.drop_index(op.f('ix_alerts_transformer_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_timestamp'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_transformers_transformer_code'), table_name='transformers')
    op.drop_table('transformers')
    op.drop_table('reports')
    op.drop_index(op.f('ix_environmental_readings_timestamp'), table_name='environmental_readings')
    op.drop_table('environmental_readings')
    # ### end Alembic commands ###
